version: '3.8'

services:
  #Broker MQTT (O mensageiro do sistema)
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mqtt_broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    restart: unless-stopped

  #Node-RED 
  nodered:
    image: nodered/node-red:latest
    container_name: node_red
    ports:
      - "80:1880"
    volumes:
      - nodered_data:/data
    restart: unless-stopped

  #InfluxDB (Banco de dados de séries temporais)
  influxdb:
    image: influxdb:2.7
    container_name: influx_db
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=rack_org
      - DOCKER_INFLUXDB_INIT_BUCKET=iot_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=token_seguro_123
    restart: unless-stopped

  #Grafana (Dashboard para visualização)
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_dashboard
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

  #Backend API (O teu motor inteligente que utiliza SQLite)
  backend:
    build: ./backend
    container_name: api_backend
    ports:
      - "8080:8080"
    volumes:
      - backend_data:/usr/src/app
    depends_on:
      - influxdb
    restart: unless-stopped

  #Frontend Nginx
  frontend:
    image: nginx:alpine
    container_name: rack_frontend
    ports:
      - "8000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    restart: unless-stopped

volumes:
  mosquitto_data:
  mosquitto_log:
  nodered_data:
  influxdb_data:
  influxdb_config:
  grafana_data:
  backend_data:
